[package]
name = "module-replace-rpc"
version = "1.2.0"
authors = ["Pendulum"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.16.0", features = ["server", "macros"] }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.35" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.35" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.35" }
module-replace-rpc-runtime-api = { path = "runtime-api" }
